[package]
name = "marble"
authors = ["Tyler Neely <t@jujit.su>"]
version = "11.7.11"
edition = "2021"
description = "garbage-collecting on-disk object store"
license = "GPL-3.0"
repository = "https://github.com/komora-io/marble"
documentation = "https://docs.rs/marble/"

[profile.release]
debug = true
panic = "abort"

[dev-dependencies]
env_logger = "0.9.0"
rand = "0.8.5"

[dependencies]
crc32fast = "1.3.2"
log = "0.4.17"
fs2 = "0.4.3"
pagetable = "0.2.6"
serde = { version = "1.0.137", features = ["derive"], optional = true }
bincode = { version = "1.3.3", optional = true }
fault-injection = "1.0.3"

rkyv = { version = "0.7", optional = true }

[[test]]
name = "crash_atomicity"
path = "tests/crash_atomicity.rs"
harness = false
